core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name= 'store'

urlpatterns = [
    path('', views.all_products, name ='all_products'),
    
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

class category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255,unique=True) 

    class Meta:
        verbose_name_plural = "categories"

 #  def get_absolute_url(self):
  #      return reverse("store:category_list", args= [self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(category, related_name='product', on_delete=models.CASCADE) 
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator') 
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4,decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural='products'
        ordering = ('-created',)

    def __str__(self):
        return self.title
     

store/views.py
from django.shortcuts import render

from .models import category, Product

def all_products(request):
    products= Product.objects.all()
    return render(request, 'store/home.html', {'products': products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <Meta charset="utf=8" />
    <title>
      {% block title %}
        chop shop
      {% endblock %}
    </title>

    <meta name="viewport" content="width=device-width" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="p-3 text-bg-dark">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              Book Store <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
            </a>
       
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
              <li><a href="#" class="nav-link px-2 text-white">Link</a></li>
             <li class= "nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">Library
                </a>
             <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url "store:all_products" %}">All</a></li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                    <a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name|title}} </a>
                </li>
                {% endfor %}
            </ul>
            </li>
            </ul>
            <form class="d-flex" >
              <input type="search" class="form-control me-2" placeholder="Search..." aria-label="Search">
              <button class = "btn btn-outline-success" type ="submit">Search</button>
            </form>
            </div>
          </div>
        </div>
      </header>
    <div id="content">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

templates/store/home.html
 {% extends "./base.html" %}
 {% load static%}
 {% block title %} chooppwer {% endblock %}

 {%block content%}
    hello page 
 {% endblock %}